export const ActionTypes = {
    SET_USER: "SET_USER",
    CREATE_TODO_LIST: "CREATE_TODO_LIST",
    DELETE_TODO_LIST: "DELETE_TODO_LIST",
    CHANGE_STATUS_TODO_LIST: "CHANGE_STATUS_TODO_LIST",
    EDIT_TODO_LIST: "EDIT_TODO_LIST",
    COMPLETE_TODO_LIST: "COMPLETE_TODO_LIST",
    INIT_TODO_LIST: "INIT_TODO_LIST"
};
